### PR TITLE
Eliminate implicit any

### PR DESCRIPTION
**Pull request by liushuyu**
This pull request fully eliminate implicit `any` types inside the repository and switch on the stricter checks in the TypeScript type-checking.

This also replaces TSLint with ESLint plus TypeScript plugin to enable better code linting.

### CODE REVIEW

**Comment by ChenLi0830** [comment]
Thanks for going the extra mile for this repo, I really appreciate it! 

However, I received some errors when running `npm test`. I have installed the dependencies through `npm ci`, is there any other prerequisites? 

```
 PASS  test/__test__/query.test.ts (30.192 s)
 PASS  test/__test__/scan.test.ts (31.431 s)
 PASS  test/__test__/delete.test.ts (33.65 s)
  ● Console

    console.log
      error is expected for non-exist-key

      at test/__test__/delete.test.ts:82:13
          at Generator.throw (<anonymous>)
          at runMicrotasks (<anonymous>)

    console.log
      error is expected for non-exist-key

      at test/__test__/delete.test.ts:101:13
          at Generator.throw (<anonymous>)
          at runMicrotasks (<anonymous>)

 FAIL  test/__test__/put.test.ts (33.886 s)
  ● put an item in partition table

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      at Object.<anonymous> (node_modules/jest-dynalite/src/setupTables.ts:3:1)
      at Object.<anonymous> (node_modules/jest-dynalite/setupTables.js:1:21)

  ● put an item in partition and sortkey table

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      at Object.<anonymous> (node_modules/jest-dynalite/src/setupTables.ts:3:1)
      at Object.<anonymous> (node_modules/jest-dynalite/setupTables.js:1:21)

  ● put an item that already exist will replace the item

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      at Object.<anonymous> (node_modules/jest-dynalite/src/setupTables.ts:3:1)
      at Object.<anonymous> (node_modules/jest-dynalite/setupTables.js:1:21)

  ● put an item with invalid params will be caught

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      at Object.<anonymous> (node_modules/jest-dynalite/src/setupTables.ts:3:1)
      at Object.<anonymous> (node_modules/jest-dynalite/setupTables.js:1:21)

  ● put an item with options

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      at Object.<anonymous> (node_modules/jest-dynalite/src/setupTables.ts:3:1)
      at Object.<anonymous> (node_modules/jest-dynalite/setupTables.js:1:21)

  ● put with default region

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      at Object.<anonymous> (node_modules/jest-dynalite/src/setupTables.ts:3:1)
      at Object.<anonymous> (node_modules/jest-dynalite/setupTables.js:1:21)

  ● put with override region

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      at Object.<anonymous> (node_modules/jest-dynalite/src/setupTables.ts:3:1)
      at Object.<anonymous> (node_modules/jest-dynalite/setupTables.js:1:21)

  ● put with undefined fileds

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      at Object.<anonymous> (node_modules/jest-dynalite/src/setupTables.ts:3:1)
      at Object.<anonymous> (node_modules/jest-dynalite/setupTables.js:1:21)

 PASS  test/__test__/get.test.ts (37.203 s)
 PASS  test/__test__/update.test.ts (45.103 s)

Test Suites: 1 failed, 5 passed, 6 total
Tests:       8 failed, 42 passed, 50 total
Snapshots:   0 total
Time:        50.906 s
```

**Comment by liushuyu** [comment]
> I received some errors when running `npm test`. I have installed the dependencies through `npm ci`, is there any other prerequisites?

I have rebased this pull request. You could also try removing `node_modules` completely and installing again via `npm i`. Sometimes `npm ci` will have surprising behaviours.

**Review by James1218 — APPROVED** [review]
Looks good! I ran the tests and all passed.

**Review by ChenLi0830 — APPROVED** [review]
Thanks, it works for me now, approved

**Pull request merged**
